export const bookGenres = [
  "Fantasy",
  "Science Fiction (Sci-Fi)",
  "Dystopian",
  "Mystery Fiction",
  "Romance",
  "Historical Fiction",
  "Thriller",
  "Literary Fiction",
  "Young Adult (YA) Fiction",
  "Biography/Memoir",
  "Classic Fiction",
  "Contemporary Fiction",
  "Horror",
  "Science Fantasy",
  "Satire",
  "Women's Fiction",
  "Graphic Novels",
  "Children's Fiction",
  "Historical Romance",
  "Adventure Fiction",
  "Crime Fiction",
  "Autobiography",
  "Fantasy Romance",
  "Steampunk",
  "Urban Fantasy",
  "Psychological Thriller",
  "Nonfiction",
  "Cookbooks",
  "Self-Help",
  "Science & Technology",
  "Art & Photography",
  "Philosophy",
  "Parenting",
  "Religion & Spirituality",
];
